version: 2
updates:
  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: [dependencies, go]
    commit-message:
      prefix: "deps(go)"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: [dependencies, javascript]
    commit-message:
      prefix: "deps(npm)"

  - package-ecosystem: docker
    directory: /infrastructure
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies, docker]
    commit-message:
      prefix: "deps(docker)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies, ci]
    commit-message:
      prefix: "deps(actions)"
