# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (C) 2026 infamousrusty

apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
