bind 0.0.0.0
protected-mode yes
save ""
appendonly no
maxmemory 100mb
maxmemory-policy allkeys-lru
tcp-backlog 511
timeout 300
tcp-keepalive 60
loglevel notice
logfile ""
rename-command FLUSHALL ""
rename-command FLUSHDB  ""
rename-command CONFIG   ""
rename-command DEBUG    ""
